name: Build
on:
  push:
    paths:
      - 'setup.py'
      - 'setup.cfg'
      - 'PKG-INFO'
      - 'thatlib/*.*'
      - '.github/workflows/*.yml'
      - '.github/workflows/*.yaml'
      - '.gitignore'

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      fail-fast: true
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    name: ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: '1.4.0'
        no-color: true  # --noColor

    - name: Set Environment Variables
      uses: allenevans/set-env@v2.0.0
      with:
        PACKAGE_NAME:          "thatlib"
        MAIN_MODULE:           "thatlib/thatlib.nim"
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true


    - name: Nimble
      run: |
        nimble -y refresh
        nimble -y install nimpy
        pip install nimporter


    - uses: juancarlospaco/nimpretty-action@main
      with:
        folders: "thatlib"


    - name: Generate Documentation (Linux)
      if: runner.os == 'Linux'
      run: nim doc --out:docs/index.html ${{ env.MAIN_MODULE }}


    - name: Compile Debug & import (Unix)
      if: runner.os == 'Linux' || runner.os == 'macOS'
      run: |
        nim c --app:lib --out:$PACKAGE_NAME.so $MAIN_MODULE
        python3 -c "print(__import__('${{ env.PACKAGE_NAME }}').__file__)"


    - name: Compile Debug & import (Windows)
      if: runner.os == 'Windows'
      run: |
        nim c --app:lib --out:${{ env.PACKAGE_NAME }}.pyd ${{ env.MAIN_MODULE }}
        python.exe -c "print(__import__('${{ env.PACKAGE_NAME }}').__file__)"
